version: '3.8'

services:
  app:
    image: gic2luis/digiauto-fe-v2:staging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXT_PUBLIC_DESKTOP_WIDTH: 1024
    ports:
      - '8085:80'
      - '3000'
    environment:
      - NODE_ENV=staging
      - PORT=3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_DESKTOP_WIDTH=1024
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    restart: always
    container_name: digiauto-fe-v2-staging
