version: '3.8'

services:
  app:
    image: gic2luis/digi-metalomec-fe-v1:staging
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXT_PUBLIC_DESKTOP_WIDTH: 1024
    ports:
      - '8089:80'
    environment:
      - NODE_ENV=staging
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_DESKTOP_WIDTH=1024
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    restart: always
    container_name: digi-metalomec-fe-staging
