import { Employee, GenericEmployee } from '@/app/types/employee/employee'

export const mapGenericEmployee = (data: any): GenericEmployee => ({
  id: data.id,
  user: {
    id: data.user.uuid,
    firstName: data.user.first_name,
    lastName: data.user.last_name,
    username: data.user.email ? data.user.email.split('@')[0] : '',
    isActive: data.user.is_active,
    fullName: `${data.user.first_name} ${data.user.last_name}`,
    email: data.user.email,
    role: data.user.role,
    company: data.user.company || '',
  },
  jobTitles: data.job_titles || [],
  collaborationStartDate: data.collaboration_start_date,
  photoUrl: data.photoUrl || '',
  performanceRating: data.performance_rating_overall || 0,
  availabilityStatus: data.availability_status || '',
  status: data.status || '',
})

export const mapEmployee = (data: any): Employee => ({
  id: data?.id || '',
  createdAt: data?.created_at || '',
  updatedAt: data?.updated_at || '',
  internalIdentifier: data?.internal_identifier || undefined,
  user: {
    id: data?.user?.id || '',
    firstName: data?.user?.first_name || '',
    lastName: data?.user?.last_name || '',
    username: data?.user?.email ? data?.user?.email.split('@')[0] : '',
    isActive: data?.user?.is_active || false,
    fullName: `${data?.user?.first_name || ''} ${data?.user?.last_name || ''}`,
    email: data?.user?.email || '',
    role: data?.user?.role || '',
    company: data?.user?.company || '',
    phoneNumber: data?.user?.phone_number || '',
    temporaryEmail: data?.user?.email_is_temporary || false,
  },
  jobTitles: data?.job_titles || [],
  department: data?.department || '',
  departmentName: data?.department_name || '',
  nationalId: data?.national_id || undefined,
  nif: data?.nif || undefined,
  socialSecurityNumber: data?.social_security_number || undefined,
  europeanHealthInsuranceCard:
    data?.european_health_insurance_card || undefined,
  collaborationStartDate: data?.collaboration_start_date || undefined,
  gender: data?.gender || '',
  maritalStatus: data?.marital_status || '',
  transportAvailable: data?.transport_available || undefined,
  geographicLocation: {
    city: data?.geographic_location?.city || '',
    municipality: data?.geographic_location?.municipality || '',
    locality: data?.geographic_location?.locality || '',
    parish: data?.geographic_location?.parish || '',
    latitude: data?.geographic_location?.latitude || null,
    longitude: data?.geographic_location?.longitude || null,
    addressFull: data?.geographic_location?.address_full || null,
  },
  preferredWorkLocation: data?.preferred_work_location || '',
  emergencyContact: data?.emergency_contact || undefined,
  educationQualification: data?.education_qualification
    ? {
        id: data?.education_qualification?.id || undefined,
        name: data?.education_qualification?.name || undefined,
        level: data?.education_qualification?.level || undefined,
      }
    : undefined,
  languages: data?.languages || [],
  photoUrl: data?.photo_url || '',
  currentLocation: data?.current_location || '',
  needsHousing: data?.needs_housing || undefined,
  housingProvided: data?.housing_provided || undefined,
  availabilityStatus: data?.availability_status || '',
  status: data?.status || '',
  workPermitExpiry: data?.work_permit_expiry || undefined,
  medicalCertificationExpiry: data?.medical_certification_expiry || undefined,
  skills: data?.skills
    ? data?.skills.map((skill: any) => ({
        id: skill.id,
        name: skill.skill_name,
        level: skill.level,
        description: skill.description || '',
        acquiredAt: skill.acquired_at || null,
        skillId: skill.skill,
      }))
    : [],
  certifications: data?.certifications
    ? data?.certifications.map((certification: any) => ({
        id: certification.id,
        certificationId: certification.certification,
        name: certification.certification_name,
        certificateUrl: certification.certificate_url,
        issuer: certification.issuer_name,
        issuedAt: certification.issued_at,
        expiresAt: certification.expires_at,
        validForDays: certification.valid_for_days,
        description: certification.description || '',
      }))
    : [],
  address: data?.address || '',
  postalCode: data?.postal_code || '',
  city: data?.city || '',
  district: data?.district || '',
  country: data?.country || '',
  dateOfBirth: data?.date_of_birth || null,
  nationality: data?.nationality || undefined,
})
