import { Employee, GenericEmployee } from '@/app/types/employee/employee'

export const mapGenericEmployee = (data: any): GenericEmployee => ({
  id: data.id,
  user: {
    id: data.user.uuid,
    firstName: data.user.first_name,
    lastName: data.user.last_name,
    username: data.user.username,
    isActive: data.user.is_active,
    fullName: `${data.user.first_name} ${data.user.last_name}`,
    email: data.user.email,
    role: data.user.role,
    companyName: data.user.company_name || '',
  },
  company: data.company,
  jobTitles: data.job_titles || [],
  collaborationStartDate: data.collaboration_start_date,
  photoUrl: data.photoUrl || '',
  performanceRating: data.performance_rating_overall || 0,
  availabilityStatus: data.availability_status || '',
  status: data.status || '',
})

export const mapEmployee = (data: any): Employee => ({
  id: data.id,
  user: {
    id: data.id,
    firstName: data.user.first_name,
    lastName: data.user.last_name,
    username: data.user.username,
    isActive: data.user.is_active,
    fullName: `${data.user.first_name} ${data.user.last_name}`,
    email: data.user.email,
    role: data.user.role,
    companyName: data.user.company_name || '',
    phoneNumber: data.user.phone_number || '',
  },
  company: data.company,
  jobTitles: data.job_titles || [],
  department: data.department || '',
  departmentName: data.department_name || '',
  nationalId: data.national_id || '',
  nif: data.nif || '',
  socialSecurityNumber: data.social_security_number || '',
  collaborationStartDate: data.collaboration_start_date || null,
  gender: data.gender || '',
  maritalStatus: data.marital_status || '',
  transportAvailable: data.transport_available || false,
  geographicAvailability: data.geographic_availability || '',
  preferredWorkLocation: data.preferred_work_location || '',
  emergencyContact: data.emergency_contact || null,
  educationQualification: {
    id: data.education_qualification.id || null,
    name: data.education_qualification.name || null,
    level: data.education_qualification.level || null,
  },
  languages: data.languages || [],
  photoUrl: data.photo_url || '',
  currentLocation: data.current_location || '',
  needsHousing: data.needs_housing || false,
  housingProvided: data.housing_provided || false,
  availabilityStatus: data.availability_status || '',
  status: data.status || '',
  workPermitExpiry: data.work_permit_expiry || null,
  medicalCertificationExpiry: data.medical_certification_expiry || null,
  skills: data.skills || [],
  certifications: data.certifications || [],
  address: data.address || '',
  postalCode: data.postal_code || '',
  city: data.city || '',
  district: data.district || '',
  country: data.country || '',
  dateOfBirth: data.date_of_birth || null,
  createdAt: data.created_at,
  updatedAt: data.updated_at,
})
